### ISSUE TITLE
Non-integer parameter for framebuffer

### ISSUE THREAD

**Issue by paulalting** [techtoys/Arduino-Memory-LCD-Driver#1]
I am looking at using your library for a 400x240 Sharp display.
For horizontal resolution you have the following in file MemoryLCD.h at line 84:
`#define GFX_FB_CANVAS_W	((DISP_HOR_RESOLUTION + 7) / 8)`
Because you add a seven and then divide by 8, the result will always be non-integer, will it not ?
So, if I have a 400x240 display, then with your equation, (400 + 7) ÷ 8 will give 50.875, which of course will be hard to use when defining an integer based framebuffer. It would likely just be 50 in this case anyhow.

I'm not sure what the extra seven bits are used for, but have you tried with a value of eight, whereby the equation will be (400 + 8) ÷ 8, giving a result of 51.

**Comment by techtoys** [comment]
The extra 7 bits is used to align the whole byte for frame buffer. It is better to use some real figures to understand this concept.

Suppose you have a LCD of 420x240. The frame buffer required for x direction = 52.5 (420/8). But we need to allocate the whole byte for that 0.5. This means we need 53 bytes. With 53 bytes we have 424 bits, the extra 4 bits ignored.

For MCU, the integer returned is always less, in this case:

uint16_t width = (420+7)/8 = 53 //not 54, integer returned is always the least whole number

What happens if we have another LCD of 396x240?

uint16_t width = (396+7)/8 = 50  //not 50.375 because width declared as uint16_t
With 50 bytes we have the least whole number of 400 bits just enough to hold 396 pixels with 4 bits ignored.

Therefore, the extra 7 bits is used to round off the frame buffer for the least whole integer required to contain all pixels in x-direction.

**Comment by paulalting** [comment]
Okay, I can better understand the reason behind the method now.
Thank you for taking the time to explain it clearly, much appreciated.

I am looking to use your library as it uses the SPI interface itself, rather than software driven as is done by Adafruit. It just seems so much better. The boards I will use it on will be SAM21D based, Adafruit Feather M0 and [Rocket Scream Mini Ultra Pro](https://www.rocketscream.com/blog/docs-item/mini-ultra-pro-hookup-guide/#tab-id-1), which is a nice little board.
There are a few things I would like to change, one being able to configure from user code, to use or not use a I/O pin and code for the clock for EXTCOMIN, and also be able to define I/O pins. Also, define screen type from user code.

**Comment by techtoys** [comment]
Nice. Definition on I/O pins is possible with header file MemoryLCD.h. There are several LCD models supported in this file. You have to comment other unwanted and leave the one you need.
